name: deploy to kirk

on:
  push:
    branches:
    - main

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
